# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-05 01:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161204_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 5, 1, 58, 39, 672914, tzinfo=utc)),
        ),
    ]
